source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.1"

use_frameworks!

target 'Example-Cocoapods' do
	pod 'DKHelper', '~> 2.1.1'
	pod 'DKDBManager', :path => '../DKDBManager.podspec'
end
