language: objective-c
osx_image: xcode7.3
xcode_workspace: DKDBManager.xcworkspace
xcode_scheme: DKDBManager
xcode_sdk: iphonesimulator9.3
xctool_args: -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES -configuration Release
sudo: false
env:
  global:
    - FRAMEWORK_NAME=DKDBManager
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update --platform iOS
  - gem install cocoapods -v '1.0.0'
before_script:
  # Manually run the tests before the `script`
  - xcodebuild -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" -configuration Release -workspace DKDBManager.xcworkspace -scheme DKDBManagerTests -sdk iphonesimulator9.3 test GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  api_key:
    secure: BBHsuN6uYaNmfF0hnhP7/r+h4GQOeX8hzlC11ijhDPysiN5drN66KTRMA0yGbBbfcku87qJicZwRK+5JIuopnRzY/1rqnX5qQIm1TXgM4hXJ5MoQzyHJapAGiUBCmundIwmKt+FYU4x7lkXPFqfrYj8WdLs2qKQT6TgQcyB4hb9WjTxmWQEMZrpRyIvVkYXHCrTqpZlg0U2+5ItsJEzyNe0pPjvFkk6B2CnxRcfZYoBPQHHcioanI2sb9r5dajBe6/Tp0VgPdWncXhLVocnkuuRN/NNVIk26LmOW7UJmj9/fsz7BYPwMo0eFI3lXzvagsEQdIdX447q1tHF/ggbkw496S/f4C5L5JCIyB7XOxbgia0kST77zsPOo5430NKUYtuu8ZxWGNnhlJDrGi66w0DMl34ZIvHjmIql00/jMIBVK3ql3Pnxa0D7VhTXoyKTzrZ3i2pzhf0QxSYAYg8BaorA3guqZ1vEl0cmeujYe3GI+KRX+qavmZ8r/XVENgXEjKT7K5Jqqce+PqkbiiMoAHCWjJp8nDXtLEwQEiBaZA/xRC4v0VXd+C+z3XBTBKGkorqpjB90WTs/DF886VC1vr++KkTej4UbB+KRyqlB+8s+qG5B281w7KiAhVIjyOXIQhuIh2pTRT0cXPKLbm/L8qOZHCbP9i4jjjRrkr/XcdqU=
  on:
    repo: kevindelord/DKDBManager
    tags: true
after_success:
  - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov)

